# Site Settings
title: DMS3
email: youremail@xyz.com
description: My Portfolio
baseurl: "/DMS3" # the subpath of your site, e.g. /blog
url: ""
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: DMS3
user_description: I make videos


# Social Media
# Remove the item if you don't need it
github_username: github_username
facebook_username: facebook_username
twitter_username: twitter_username
instagram_username: instagram_username
linkedin_username: linkedin_username
medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
